config/routes.rb
Rails.application.routes.draw do

  authenticated do
    root :to => 'posts#new', as: :authenticated
  end

  root to: "welcome#index"

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :posts

  get '/tos', :to => 'welcome#tos', :as => :tos
  get '/privacy', :to => 'welcome#privacy', :as => :privacy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, :foreign_key => "users_id", :class_name => "User"
  validates :title, :presence => true
  validates :body, :presence => true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  has_many :posts, :foreign_key => "users_id", :class_name => "Post", dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable,
         omniauth_providers: [:google_oauth2]

   def self.from_omniauth(access_token)
     data = access_token.info
     user = User.where(email: data['email']).first

     unless user
         user = User.create(
            email: data['email'],
            password: Devise.friendly_token[0,20]
         )
     end
     user
   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
#app/controllers/posts_controller.rb

class PostsController < ApplicationController
  before_action :find_post, only: [:edit, :update, :show, :delete]
  before_action :authenticate_user!

  # Index action to render all posts
  def index
    @posts = current_user.posts
    @grouped_posts = {}


    @posts.each do |post|
      if @grouped_posts[post.title]
        @grouped_posts[post.title] << post
      else
        @grouped_posts[post.title] = [post]
      end
    end

    @posts_count = current_user.posts.count
    @cars_ridden = @grouped_posts.keys.count
    @matched_cars = 0

    @grouped_posts.each do |key, value|
      if value.length > 1
        @matched_cars += 1
      end
    end
  end

  # New action for creating post
  def new
    @post = Post.new
  end

  # Create action saves the post into database
  def create
    post = Post.new(
      title: post_params['title'],
      car_end: post_params['car_end'],
      body: post_params['body'],
      users_id: current_user.id)
    if post.valid?
      if (current_user.posts.find_by_title(post_params['title']))
        flash[:notice] = "Match! You've been on this car before."
      end
      post.save!
      redirect_to post_path(post)
    else
      flash[:alert] = "Error creating new post!"
      @post = post
      render :new
    end
  end

  # Edit action retrives the post and renders the edit page
  def edit
  end

  # Update action updates the post with the new information
  def update
    if @post.update_attributes(post_params)
      flash[:notice] = "Successfully updated post!"
      redirect_to post_path(@post)
    else
      flash[:alert] = "Error updating post!"
      render :edit
    end
  end

  # The show action renders the individual post after retrieving the the id
  def show
    @post = Post.find(params[:id])
    @related_posts = []
    current_user.posts.where(title: @post.title).each do |p|
      if p.id != @post.id
        @related_posts << p
      end
    end
  end

  # The destroy action removes the post permanently from the database
  def destroy
    if @post.destroy
      flash[:notice] = "Successfully deleted post!"
      redirect_to posts_path
    else
      flash[:alert] = "Error updating post!"
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :car_end, :body, :utf8, :authenticity_token, :commit, :user_id)
  end

  def find_post
    @post = Post.find(params[:id])
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
      # You need to implement the method below in your model (e.g. app/models/user.rb)
      @user = User.from_omniauth(request.env['omniauth.auth'])

      if @user.persisted?
        flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
        sign_in_and_redirect @user, event: :authentication
      else
        session['devise.google_data'] = request.env['omniauth.auth'].except(:extra) # Removing extra as it can overflow some session stores
        redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
      end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def privacy
  end

  def tos
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def resource_class
    User
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BART Journal</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light mb-4">
      <a class="navbar-brand font-weight-light" href="/">BART Journal</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <% if current_user %>
      <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to "All Posts", posts_url(), { class: "btn btn-link" } %>
          </li>
          <li class="nav-item">
            <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "btn btn-outline-primary") %>
          </li>
        </ul>
      </div>
      <% else %>
      <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to('Log In', new_user_session_path, class: "btn btn-outline-primary") %>
          </li>
        </ul>
      </div>
      <% end %>
    </nav>

    <div class="container main-content">
      <div class="row">
        <div class="col-md-8 offset-md-2 mt-2">
          <% if notice %>
            <p class="alert alert-success"><%= notice %></p>
          <% end %>
          <% if alert %>
            <p class="alert alert-danger"><%= alert %></p>
          <% end %>
        </div>
      </div>

      <%= yield %>
    </div>
  </body>

  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-131797977-1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-131797977-1');
  </script>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for @post do |f| %>
  <% if @post.errors.any? %>
  <div class="row">
    <div class="mt-2 col-md-8 offset-md-2">
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
        <li class="text-danger">
          <%= msg %>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
  <% end %>
  <div class="row">
    <div class="mt-2 col-md-8 offset-md-2">
      <div class="card">
        <div class="card-body">
          <div class="form-inline mb-2">
            <div class="input-group">
              <div class="input-group-prepend">
                <div class="input-group-text">Car #</div>
              </div>
              <%= number_field("post", "title", class: "form-control", pattern: "[0-9]*", inputmode: "numeric", placeholder: "e.g. 1622") %>
            </div>

          </div>
          <div class="btn-group btn-block btn-group-toggle" data-toggle="buttons">
            <label class="btn btn-outline-primary pl-4 pr-4 active">
              X
              <%= radio_button("post", "car_end", "X", { checked: true }) %>
            </label>
            <label class="btn btn-outline-primary pl-4 pr-4">
              Y
              <%= radio_button("post", "car_end", "Y") %>
            </label>
          </div>
          <hr />
          <div class="form-group">
            <%= text_area("post", "body", class: "form-control", placeholder: "What's special about today?", rows: 4) %>
          </div>

          <div class="form-group">
            <%= f.button :submit, class: "btn btn-primary btn-block" %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="col-md-8 offset-md-2 mt-3">

  <h2 class="font-weight-light" >Edit Post</h2>
</div>

<%= render "posts/form" %>

app/views/posts/index.html.erb
<div class="row">
  <div class="col-md-8 offset-md-2 text-center mt-2">
    <div class="btn-group btn-block">
      <a class="btn btn-light" data-toggle="collapse" href="#stats-container" role="button" aria-expanded="false" aria-controls="stats-container">
        Show Stats
      </a>
      <%= link_to "New Post", new_post_path(), { class: "btn btn-primary" } %>
    </div>
  </div>
</div>

<div class="row collapse" id="stats-container">
  <div class="col-md-8 offset-md-2">
    <div class="card-group mt-2">
      <div class="card col-md-4">
        <div class="card-body text-center">
          <h5 class="font-weight-light card-title"><%= @posts_count %></h5>
          <p>Posts</p>
        </div>
      </div>
      <div class="card col-md-4 text-center">
        <div class="card-body">
          <h5 class="font-weight-light card-title"><%= @cars_ridden %></h5>
          <p>Cars Ridden</p>
        </div>
      </div>
      <div class="card col-md-4 text-center">
        <div class="card-body">
          <h5 class="font-weight-light card-title"><%= @matched_cars %></h5>
          <p>Cars with more than one ride</p>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-8 offset-md-2">
    <% if @grouped_posts.length > 0 %>
      <% @grouped_posts.each do |key, posts| %>
      <div class="card mt-2">
        <h4 class="font-weight-light card-header">Car <%= key %></h4>

        <ul class="list-group list-group-flush">
          <%  posts.each do |post| %>
          <li class="list-group-item">
            <span class="card-text"><%= raw(post.body).truncate(100) %></span>
            <span class="card-text text-muted">(<%= post.created_at.strftime('%b %d, %Y') %>)</span>
            <%= link_to "Read More", post_path(post), { class: "btn btn-link float-right" } %>
          </li>
          <% end %>
        </ul>
      </div>
      <% end %>
    <% else %>
      <div class="card border-primary mt-2">
        <div class="card-body">
          <h2 class="font-weight-light card-heading">You haven't logged any rides yet.</h2>
          <p class="text-muted">BART Journal allows you to keep a daily journal based on your commute. Know the last time you were on your BART car and what you were thinking about.</p>
          <%= link_to 'Add New Post', new_post_path(), { class: 'card-link' } %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<%= render "posts/form" %>

app/views/posts/show.html.erb
<div class="row">
  <div class="col-md-8 offset-md-2">
    <div class="card mb-2">
      <div class="card-header">
        This Post
        <%= link_to "Edit", edit_post_path(@post), { class: "btn btn-link float-right" } %>
      </div>
      <div class="card-body">
        <h4 class="text-center">Car: <%= @post.title %> <%= @post.car_end %></h4>
        <p class="text-center text-muted"><%= @post.created_at.strftime('%b %d, %Y') %></p>
        <div>
          <p><%= raw @post.body %></p>
        </div>
      </div>
    </div>
  </div>
</div>

<% if @related_posts.length > 0 %>
<div class="row">
  <div class="col-md-8 offset-md-2">
    <div class="card">
      <div class="card-header">
        Other Posts from Car <%= @post.title %>
      </div>
      <ul class="list-group list-group-flush">
        <% @related_posts.each do |post| %>
        <% if post.id != @post.id %>
        <div class="list-group-item">
          <span class="text-center">Car: <%= post.title %> <%= post.car_end %></span>
          <span class="text-center text-muted"><%= post.created_at.strftime('%b %d, %Y') %></span>
          <span><%= raw(post.body).truncate(100) %></span>
          <%= link_to "View", post_path(post), { class: "btn btn-link float-right" } %>
        </div>
        <% end %>
        <% end %>
      </ul>
    </div>

    <%= link_to "Add another post", new_post_path, { class: "btn btn-primary btn-block mt-2" } %>
  </div>
</div>
<% end %>

app/views/welcome/index.html.erb
<div class="row">
  <div class="col-md-5">
    <h2 class="font-weight-light mt-5">BART Journal is a simple diary for your commute.</h2>
    <p class="mt-4">Add your BART car number and a journal entry. BART Journal will show you when you've been on the same car twice.</p>
  </div>
  <div class="col-md-6 offset-md-1">
    <%= render "devise/registrations/new" %>
  </div>
</div>

app/views/welcome/privacy.html.erb
<div class="card mt-2">
  <div class="card-body">
    <h2>Privacy Policy</h2>
    <p>Your privacy is important to us. It is BART Journal's policy to respect your privacy regarding any information we may collect from you across our website, <a href="http://www.bartjournal.com">http://www.bartjournal.com</a>, and other sites we own and operate.</p>
    <p>We only ask for personal information when we truly need it to provide a service to you. We collect it by fair and lawful means, with your knowledge and consent. We also let you know why we’re collecting it and how it will be used.</p>
    <p>We only retain collected information for as long as necessary to provide you with your requested service. What data we store, we’ll protect within commercially acceptable means to prevent loss and theft, as well as unauthorised access, disclosure, copying, use or modification.</p>
    <p>We don’t share any personally identifying information publicly or with third-parties, except when required to by law.</p>
    <p>Our website may link to external sites that are not operated by us. Please be aware that we have no control over the content and practices of these sites, and cannot accept responsibility or liability for their respective privacy policies.</p>
    <p>You are free to refuse our request for your personal information, with the understanding that we may be unable to provide you with some of your desired services.</p>
    <p>Your continued use of our website will be regarded as acceptance of our practices around privacy and personal information. If you have any questions about how we handle user data and personal information, feel free to contact us.</p>
    <p>This policy is effective as of 2 January 2019.</p>
  </div>
</div>

app/views/welcome/tos.html.erb
<div class="card mt-2">
  <div class="card-body">
    <h2 class="font-weight-light">BART Journal Terms of Service</h2>
    <h3 class="font-weight-light">1. Terms</h3>
    <p>By accessing the website at <a href="https://www.bartjournal.com">https://www.bartjournal.com</a>, you are agreeing to be bound by these terms of service, all applicable laws and regulations, and agree that you are responsible for compliance with any applicable local laws. If you do not agree with any of these terms, you are prohibited from using or accessing this site. The materials contained in this website are protected by applicable copyright and trademark law.</p>
    <h3 class="font-weight-light">2. Use License</h3>
    <ol type="a">
      <li>Permission is granted to temporarily download one copy of the materials (information or software) on BART Journal's website for personal, non-commercial transitory viewing only. This is the grant of a license, not a transfer of title, and under this license you may not:
        <ol type="i">
          <li>modify or copy the materials;</li>
          <li>use the materials for any commercial purpose, or for any public display (commercial or non-commercial);</li>
          <li>attempt to decompile or reverse engineer any software contained on BART Journal's website;</li>
          <li>remove any copyright or other proprietary notations from the materials; or</li>
          <li>transfer the materials to another person or "mirror" the materials on any other server.</li>
        </ol>
      </li>
      <li>This license shall automatically terminate if you violate any of these restrictions and may be terminated by BART Journal at any time. Upon terminating your viewing of these materials or upon the termination of this license, you must destroy any downloaded materials in your possession whether in electronic or printed format.</li>
    </ol>
    <h3 class="font-weight-light">3. Disclaimer</h3>
    <ol type="a">
      <li>The materials on BART Journal's website are provided on an 'as is' basis. BART Journal makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties including, without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights.</li>
      <li>Further, BART Journal does not warrant or make any representations concerning the accuracy, likely results, or reliability of the use of the materials on its website or otherwise relating to such materials or on any sites linked to this site.</li>
    </ol>
    <h3 class="font-weight-light">4. Limitations</h3>
    <p>In no event shall BART Journal or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption) arising out of the use or inability to use the materials on BART Journal's website, even if BART Journal or a BART Journal authorized representative has been notified orally or in writing of the possibility of such damage. Because some jurisdictions do not allow limitations on implied warranties, or limitations of liability for consequential or incidental damages, these limitations may not apply to you.</p>
    <h3 class="font-weight-light">5. Accuracy of materials</h3>
    <p>The materials appearing on BART Journal's website could include technical, typographical, or photographic errors. BART Journal does not warrant that any of the materials on its website are accurate, complete or current. BART Journal may make changes to the materials contained on its website at any time without notice. However BART Journal does not make any commitment to update the materials.</p>
    <h3 class="font-weight-light">6. Links</h3>
    <p>BART Journal has not reviewed all of the sites linked to its website and is not responsible for the contents of any such linked site. The inclusion of any link does not imply endorsement by BART Journal of the site. Use of any such linked website is at the user's own risk.</p>
    <h3 class="font-weight-light">7. Modifications</h3>
    <p>BART Journal may revise these terms of service for its website at any time without notice. By using this website you are agreeing to be bound by the then current version of these terms of service.</p>
    <h3 class="font-weight-light">8. Governing Law</h3>
    <p>These terms and conditions are governed by and construed in accordance with the laws of California and you irrevocably submit to the exclusive jurisdiction of the courts in that State or location.</p>
  </div>
</div>